name: CI

on: 
  pull_request:
  push:
  
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Copy single file to remote
      uses: garygrossgarten/github-action-scp@v0.7.1
      with:
        local: ajax
        remote: /var/www/erp-server
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.PASSWORD }}
    - name: Run SSH command
      uses: garygrossgarten/github-action-ssh@v0.6.3
      with:
        command: cd /var/www/erp-server; ls -l
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.PASSWORD }}
